# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-04 13:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileSheet', '0003_auto_20170504_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='job',
            field=models.CharField(choices=[('J', 'Jedi'), ('S', 'Smuggler'), ('B', 'Bounty hunter'), ('P', 'Politician')], max_length=1),
        ),
    ]
